development:
  adapter: mysql2
  database: wud_db
  encoding: utf8
  username: root
  password: pass
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: wud_20130320_test
  encoding: utf8
  username: root
  password: pass
  socket: /tmp/mysql.sock

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
